services:
  - type: web
    name: ckd-deep-learning-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11
